# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a28ad6bf8ef0888a5e8b4bb1305f8ced5516ebc5940a6bd926d2e2aaf5786a99ef4558979523f04eea27c67047e290e88afb143eade6ef18ce0467d31387c29

test:
  secret_key_base: 2b78fe233c9c69cca1d16230fd1cf317c9df4b1ee3b70a83234433b47ea9dc4432dc036b73a26d14e55c8cdbf199fbfb0665bc2c8178c73ff197117bf7ed76c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
